spring:
  application:
    name: url-shortener
  profiles:
    active: prod
server:
  port: ${port:8080}
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/url-shortener-db
    username: url-shortener-usr
    password: url-shortener-passwd#123
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
  redis:
    host: localhost
    port: 6379
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/url-shortener-db}
    username: ${SPRING_DATASOURCE_USERNAME:url-shortener-usr}
    password: ${SPRING_DATASOURCE_PASSWORD:url-shortener-passwd#123}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
  redis:
    host: redis
